#!/bin/env bash

downloadLocation="$HOME/Downloads"
installLocation="$HOME/.local/bin/neovim"
tag=stable

if [ ! -d $downloadLocation ]; then
    mkdir $downloadLocation
fi

if [ -d $installLocation ]; then
    echo "Neovim - install directory exists. Removing"
    rm -rf $installLocation
fi


wget "https://github.com/neovim/neovim/releases/download/$tag/nvim-linux-x86_64.tar.gz" -P $downloadLocation
tar -xvzf $(downloadLocation)/nvim-linux-x86.tar.gz

mv $downloadLocation/nvim-linux-x87 $installLocation
rm $downloadLocation/nvim-linux-x86.tar.gz
